version: 2.1

jobs:
  docker-job:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: echo "hello"

workflows:
  main:
    jobs:
      - docker-job
