version: 2.1

orbs:
  test1: vjpandian/test1@0.0.1

jobs:
  docker-job:
    docker:
      - image: cimg/base:current
    resource_class: small
    steps:
      - checkout
      - run: echo "hello"
      - test1/test

workflows:
  main:
    jobs:
      - docker-job
